apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
spec:
  selector:
    app: prometheus-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9090